var res = {
//		Page1_png : "res/page1.png",
//		PageWord1_png:"res/pageWord1.png",
//		Page2_png : "res/page2.png",
//		PageWord2_png:"res/pageWord2.png",
//		Page3_png : "res/page3.png",
//		PageWord3_png:"res/pageWord3.png",
//		Page4_png : "res/page4.png",
//		PageWord4_png:"res/pageWord4.png",
//		Page5_png : "res/page5.png",
//		PageWord5_png:"res/pageWord5.png",
//		Page6_png : "res/page6.png",
//		PageWord6_png:"res/pageWord6.png",
//		Page7_png : "res/page7.png",
//		PageWord7_png:"res/pageWord7.png",
//		Page8_png : "res/page8.png",
//		PageWord8_png:"res/pageWord8.png",
//		Page9_png : "res/page9.png",
//		PageWord9_png:"res/pageWord9.png",
//		Page10_png : "res/page10.png",
//		PageWord10_png:"res/pageWord10.png",
//		Page11_png : "res/page11.png",
//		PageWord11_png:"res/pageWord11.png",
		firstPage_png: "res/firstPage.png",
		firstPage_plist: "res/firstPage.plist",
		
		wp1_png:"res/wpic/p1.png",
		wp2_png:"res/wpic/p2.png",
		wp3_png:"res/wpic/p3.png",
		wp4_png:"res/wpic/p4.png",
		wp5_png:"res/wpic/p5.png",
		wp6_png:"res/wpic/p6.png",
		wp7_png:"res/wpic/p7.png",
		wp8_png:"res/wpic/p8.png",
		wp9_png:"res/wpic/p9.png",
		wp10_png:"res/wpic/p10.png",
		wp11_png:"res/wpic/p11.png",
		wp12_png:"res/wpic/p12.png",
		
		wpw1_png:"res/wpic/pw1.png",
		wpw2_png:"res/wpic/pw2.png",
		wpw3_png:"res/wpic/pw3.png",
		wpw4_png:"res/wpic/pw4.png",
		wpw5_png:"res/wpic/pw5.png",
		wpw6_png:"res/wpic/pw6.png",
		wpw7_png:"res/wpic/pw7.png",
		wpw8_png:"res/wpic/pw8.png",
		wpw9_png:"res/wpic/pw9.png",
		wpw10_png:"res/wpic/pw10.png",
		wpw11_png:"res/wpic/pw11.png",
		wpw12_png:"res/wpic/pw12.png",
		
		
		hp1_png:"res/hpic/p1.png",
		hp2_png:"res/hpic/p2.png",
		hp3_png:"res/hpic/p3.png",
		hp4_png:"res/hpic/p4.png",
		hp5_png:"res/hpic/p5.png",
		hp6_png:"res/hpic/p6.png",
		hp7_png:"res/hpic/p7.png",
		hp8_png:"res/hpic/p8.png",
		hp9_png:"res/hpic/p9.png",
		hp10_png:"res/hpic/p10.png",
		hp11_png:"res/hpic/p11.png",
		hp12_png:"res/hpic/p12.png",

		hpw1_png:"res/hpic/pw1.png",
		hpw2_png:"res/hpic/pw2.png",
		hpw3_png:"res/hpic/pw3.png",
		hpw4_png:"res/hpic/pw4.png",
		hpw5_png:"res/hpic/pw5.png",
		hpw6_png:"res/hpic/pw6.png",
		hpw7_png:"res/hpic/pw7.png",
		hpw8_png:"res/hpic/pw8.png",
		hpw9_png:"res/hpic/pw9.png",
		hpw10_png:"res/hpic/pw10.png",
		hpw11_png:"res/hpic/pw11.png",
		hpw12_png:"res/hpic/pw12.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}